name: CI minikube
on:
   workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: |
         kubectl create ns e2e&&minikube addons enable ingress&&eval $(minikube -p minikube docker-env) \
         &&echo "$(minikube ip) gban-e2e-host" |sudo tee -a /etc/hosts&&echo '====================\r\n'\
         cat /etc/hosts&& \
         kubectl create secret docker-registry gban-registry --docker-server=ghcr.io/btech-devcenter --docker-username=$GITHUB_ACTOR --docker-password=$GITHUB_TOKEN --docker-email=test@none.none -n e2e&&\
         echo $GITHUB_TOKEN | docker login -u $GITHUB_ACTOR ghcr.io --password-stdin&& \
         docker pull ghcr.io/btech-devcenter/gban-config-server:latest
    - name: try helm
      run: helm status gban-e2e -n e2e
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t local/example .
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube
      run:
        kubectl apply -f deploy-to-minikube.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service example --url
        echo "------------------opening the service------------------"
        curl $(minikube service example --url)        
