name: Run Python 

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
     - name: Display the path
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_PARAM: testValue
       run: |
         import requests
         import os
         for item, value in os.environ.items():
            print('{}: {}'.format(item, value))
         session = requests.Session()
         session.headers['Authorization'] = 'token ${GITHUB_TOKEN}'
         url = "https://api.github.com/repos/btech-devcenter/gpfgba-e2e-tests/dispatches"
         data = {"event_type": "e2e-trigger"}
         res = session.post(url, json={"event_type": "e2e-trigger"})
         print( res.content )
       shell: python
