name: Run Python 

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
     - name: Display the path
       run: |
        import os
        print(os.environ['PATH'])
       shell: python {0}
