name: Run Python 

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 2.7 #install the python needed
          run: |
            python -m pip install --upgrade pip
            pip install requests
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import requests
            gitHubToken = "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"
            session = requests.Session()
            session.headers['Authorization'] = 'token %s' % gitHubToken
            url = "https://api.github.com/repos/btech-devcenter/gpfgba-e2e-tests/dispatches"
            data = {"event_type": "e2e-trigger"}
            res = session.post(url, json={"event_type": "e2e-trigger"})
            print res.content 
